# Generated by Django 3.0.6 on 2020-08-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='statu',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
