# Generated by Django 3.0.6 on 2020-08-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_test_statu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='statu',
            new_name='st',
        ),
    ]
